name: RGV3
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.8
    - pip
    - numpy
    - scipy
    - matplotlib
    - tqdm
    - pip:
        - torch
        - glfw
        - tensorboard
        - mujoco-py<2.2,>=2.0
        - pytz
        - pandas
